### ISSUE TITLE
Onboarding Checklist Issue

### ISSUE THREAD

**Issue by epierotti3** [code4sac/trash-ai#158]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Dependencies

None

### Overview

We need to create a checklist of items to do whenever a new volunteer joins TrashAI so that they know exactly where to get started. This should make this process consistent and efficient.

### Action Items

THIS ISSUE WILL NEVER CLOSE! Simply follow the instructions below to create a thread of comments every time we onboard new volunteers.
- [ ]  Copy template to comment below
- [ ]  Add name of person into comment
- [ ]  Check off each item as they are completed.

```
#### Onboard [replace with name] 
- [ ] GitHub
     - [ ] Add to code for sacramento team
     - [ ] Add to trash-ai team
     - [ ] Confirm that their name is on their Github (makes it easier to know who is working on what)
- [ ] Slack channel membership
     - [ ] ```#proj-trash-ai```
- [ ] [Google Drive](https://drive.google.com/drive/folders/1Hk4LdyVFcVPGCAd5bncswaxLKX1bDuNe)
     - [ ] Add to drive as Viewer first, change to Contributor as needed
(As of right now there are a few different google drives, which is another problem, but make sure the new volunteer is added to whatever they need)
- [ ] [Figma](https://www.figma.com/file/TBRSf0DLvmqnuV1hLNkwbo/Trash-AI?type=design&node-id=0-1&t=SXt8TycSQC7pZv9j-0) (as needed)
     - [ ] send them an invite
     - [ ] make sure they accept
- [ ] Walk them through the [project board](https://github.com/orgs/code4sac/projects/13)
     - [ ] talk about open issues

```

**Comment by epierotti3** [comment]
Here's an example:

#### Onboard Elizabeth Pierotti
- [x] Slack channel membership
  - [x] ```#proj-trash-ai```
- [x] [Google Drive](https://drive.google.com/drive/folders/1Hk4LdyVFcVPGCAd5bncswaxLKX1bDuNe)
   - [x] Add to drive as Viewer first, change to Contributor as needed
(As of right now there are a few different google drives, which is another problem, but make sure the new volunteer is added to whatever they need)
- [x] GitHub
     - [x] Add to code for sacramento team
     - [x] Add to trash-ai team
     - [x] Confirm that their name is on their Github (makes it easier to know who is working on what)
- [x] [Figma](https://www.figma.com/file/TBRSf0DLvmqnuV1hLNkwbo/Trash-AI?type=design&node-id=0-1&t=SXt8TycSQC7pZv9j-0) (as needed)
  - [x] send them an invite
  - [x] make sure they accept
- [x] Walk them through the [project board](https://github.com/orgs/code4sac/projects/13) and talk about open issues

**Comment by epierotti3** [comment]
#### Onboard Jacob @gandalfthegreenery 
- [x] GitHub
     - [x] Add to code for sacramento team (Brianda needs to do this)
     - [ ] [Add to trash-ai team](https://github.com/orgs/code4sac/teams/trashai) (Elizabeth can do this)
     - [x] Confirm that their name is on their Github (makes it easier to know who is working on what) - > "gandalfthegreenery"
- [x] Slack channel membership
     - [x] ```#proj-trash-ai```
- [x] [Google Drive](https://drive.google.com/drive/folders/1Hk4LdyVFcVPGCAd5bncswaxLKX1bDuNe)
     - [x] Add to drive as Viewer first, change to Contributor as needed
(As of right now there are a few different google drives, which is another problem, but make sure the new volunteer is added to whatever they need)
- [ ] [Figma](https://www.figma.com/file/TBRSf0DLvmqnuV1hLNkwbo/Trash-AI?type=design&node-id=0-1&t=SXt8TycSQC7pZv9j-0) (as needed)
     - [ ] send them an invite
     - [ ] make sure they accept
- [x] Walk them through the [project board](https://github.com/orgs/code4sac/projects/13)
     - [x] talk about open issues

**Comment by epierotti3** [comment]
#### Onboard Ade
- [x] GitHub
     - [x] Add to code for sacramento team
     - [ ] Add to trash-ai team
     - [x] Confirm that their name is on their Github (makes it easier to know who is working on what)
- [x] Slack channel membership
     - [x] ```#proj-trash-ai```
- [x] [Google Drive](https://drive.google.com/drive/folders/1Hk4LdyVFcVPGCAd5bncswaxLKX1bDuNe)
     - [x] Add to drive as Viewer first, change to Contributor as needed
(As of right now there are a few different google drives, which is another problem, but make sure the new volunteer is added to whatever they need)
- [ ] [Figma](https://www.figma.com/file/TBRSf0DLvmqnuV1hLNkwbo/Trash-AI?type=design&node-id=0-1&t=SXt8TycSQC7pZv9j-0) (as needed)
     - [ ] send them an invite
     - [ ] make sure they accept
- [x] Walk them through the [project board](https://github.com/orgs/code4sac/projects/13)
     - [x] talk about open issues

**Comment by epierotti3** [comment]
#### Onboard Ruoyu Li
- [ ] GitHub -> username is RuoyuLII
     - [ ] Add to code for sacramento team
     - [ ] Add to trash-ai team
     - [ ] Confirm that their name is on their Github (makes it easier to know who is working on what)
- [x] Slack channel membership
     - [x] ```#proj-trash-ai```
- [x] [Google Drive](https://drive.google.com/drive/folders/1Hk4LdyVFcVPGCAd5bncswaxLKX1bDuNe)
     - [x] Add to drive as Viewer first, change to Contributor as needed
(As of right now there are a few different google drives, which is another problem, but make sure the new volunteer is added to whatever they need)
- [ ] [Figma](https://www.figma.com/file/TBRSf0DLvmqnuV1hLNkwbo/Trash-AI?type=design&node-id=0-1&t=SXt8TycSQC7pZv9j-0) (as needed)
     - [ ] send them an invite
     - [ ] make sure they accept
- [ ] Walk them through the [project board](https://github.com/orgs/code4sac/projects/13)
     - [ ] talk about open issues
